include:
  - services/servicediscovery/docker-compose.yaml
  - services/shapemanagement/docker-compose.yaml
  - services/furnituremanagement/docker-compose.yaml
  - services/gateway/docker-compose.yaml
  - services/gui/docker-compose.yaml
