services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      EUREKA_URL: "service-discovery:8761"
    depends_on:
      - service-discovery
