services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management
    environment:
      EUREKA_URL: "service-discovery:8761"
      DB_TYPE: "postgresql"
      DB_HOST: "user-database"
      DB_PORT: "5432"
      DB_NAME: "user-management"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - service-discovery
    networks:
      - default
      - user-network
  user-database:
    image: postgres:17
    container_name: user-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-management
    restart: always
    networks:
      - user-network
    volumes:
      - user-db-data:/var/lib/postgresql/data
networks:
  user-network:
    driver: bridge

volumes:
  user-db-data:
