const InstructionCommands = Object.freeze({
  CREATE_RECTANGLE: "CREATE_RECTANGLE",
  CREATE_ELLIPSE: "CREATE_ELLIPSE",
  CREATE_ARC: "CREATE_ARC",
  CREATE_POLYGON: "CREATE_POLYGON",
  BEGIN_CONTAINER: "BEGIN_CONTAINER",
  END_CONTAINER: "END_CONTAINER",
  CREATE_GENERIC: "CREATE_GENERIC",
});

export default InstructionCommands;
