import { JetBrains_Mono } from "next/font/google";
import PrimeProvider from "./PrimeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PrimeProvider>{children}</PrimeProvider>
      </body>
    </html>
  );
}
