import PrimeProvider from "./PrimeProvider";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PrimeProvider>
          <StoreProvider>{children}</StoreProvider>
        </PrimeProvider>
      </body>
    </html>
  );
}
