services:
  shape-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shape-management
    environment:
      EUREKA_URL: "service-discovery:8761"
      DB_TYPE: "postgresql"
      DB_HOST: "shape-database"
      DB_PORT: "5432"
      DB_NAME: "shape-management"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - service-discovery
    networks:
      - default
      - shape-network
  shape-database:
    image: postgres:17
    container_name: shape-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shape-management
    restart: always
    networks:
      - shape-network
    volumes:
      - shape-db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
networks:
  shape-network:
    driver: bridge

volumes:
  shape-db-data:
